
const luresDB = [
    {
        id: "0",
        precio: "10.99" ,
        nombre: "Rapala X-Rap",
        tipo: "Señuelo de superficie",
        descripcion: "Señuelo de acción de natación agresiva, imita a un pez herido.",
    },
    {
        id: "1",
        precio: "5.99",
        nombre: "Spinnerbait",
        tipo: "Señuelo tipo spinner",
        descripcion: "Señuelo con hélice que crea vibraciones y destellos para atraer al pez.",
    },
    {
        id: "2",
        precio: "11.99",
        nombre: "Crankbait",
        tipo: "Señuelo de profundidad",
        descripcion: "Señuelo diseñado para alcanzar profundidades específicas rápidamente.",
    },
    {
        id: "3",
        precio: "18.99",
        nombre: "Jerkbait",
        tipo: "Señuelo suspendido",
        descripcion: "Señuelo que simula a un pez herido y se mantiene suspendido en el agua.",
    },
    {
        id: "4",
        precio: "14.99",
        nombre: "Popper",
        tipo: "Señuelo de superficie",
        descripcion: "Señuelo que crea un chapoteo al imitar un pez pequeño en la superficie.",
    },
    {
        id: "5",
        precio: "25.99",
        nombre: "Swimbait",
        tipo: "Señuelo articulado",
        descripcion: "Señuelo con múltiples segmentos que imita el movimiento de un pez real.",
    },
    {
        id: "6",
        precio: "20.99",
        nombre: "Heddon Torpedo",
        tipo: "Señuelo de superficie",
        descripcion: "Señuelo clásico con forma de torpedo que crea movimientos erráticos.",
    },
    {
        id: "7",
        precio: "4.99",
        nombre: "Cuchara ondulante",
        tipo: "Señuelo de cucharilla",
        descripcion: "Señuelo que imita un pez pequeño en movimiento constante.",
    },
    {
        id: "8",
        precio: "23.99",
        nombre: "Sinking Minnow",
        tipo: "Señuelo hundidor",
        descripcion: "Señuelo que se hunde lentamente para atraer a peces en capas más profundas.",
    },
    {
        id: "9",
        precio: "3.99",
        nombre: "Wacky Worm",
        tipo: "Señuelo blando",
        descripcion: "Señuelo de goma que imita un gusano para la pesca de lucio.",
    },
    {
        id: "10",
        precio: "4.99",
        nombre: "Jig Head",
        tipo: "Señuelo con cabeza plomada",
        descripcion: "Señuelo con anzuelo y cabeza plomada para pesca vertical o en el fondo.",
    },
    {
        id: "11",
        precio: "5.99",
        nombre: "Ned Rig",
        tipo: "Señuelo finesse",
        descripcion: "Señuelo de pesca finesse con forma de gusano para capturas sutiles.",
    },
    {
        id: "12",
        precio: "7.99",
        nombre: "Chatterbait",
        tipo: "Señuelo vibratorio",
        descripcion: "Señuelo con acción vibrante que imita presas en movimiento.",
    },
    {
        id: "13",
        precio: "7.99",
        nombre: "Frog Hollow Body",
        tipo: "Señuelo de ranita hueca",
        descripcion: "Señuelo que imita una rana en la superficie del agua.",
    },
    {
        id: "14",
        precio: "6.99",
        nombre: "Spoon Lure",
        tipo: "Señuelo tipo cuchara",
        descripcion: "Señuelo de metal que imita el brillo de un pez pequeño.",
    }
];

export default luresDB